In [2]:
import pandas as pd
import sqlite3

In [4]:
df = pd.read_csv('../dataset/EAFC26.csv')

In [5]:
conn = sqlite3.connect(':memory:')

In [6]:
df.to_sql('eafc26', conn, index=False)

17873

In [7]:
# Tabel A: Profil Pemain
df[['ID', 'Name', 'GENDER', 'Age', 'Nation', 'League', 'Team', 'Position']].to_sql('players', conn, index=False)
# Tabel B: Statistik Pemain
df[['ID', 'OVR', 'PAC', 'SHO', 'PAS', 'DRI', 'DEF', 'PHY']].to_sql('stats', conn, index=False)

print("Database siap digunakan")

Database siap digunakan

In [14]:
query_dasar = """
SELECT 
    Name, 
    Age, 
    Team, 
    OVR, 
    Finishing 
FROM 
    eafc26
WHERE 
    Age <= 23 AND Finishing > 85
ORDER BY 
    Finishing DESC
LIMIT 5;
"""
# Menjalankan query dan menampilkannya dalam format rapi
pd.read_sql(query_dasar, conn)

                 Name  Age               Team  OVR  Finishing
0    Melchie Dumornay   22         OL Lyonnes   86         89
1     Jude Bellingham   22        Real Madrid   90         88
2    Salma Paralluelo   22       FC Barcelona   84         88
3       Jamal Musiala   23  FC Bayern München   88         86
4  Agnes Beever-Jones   22            Chelsea   78         86

In [19]:
query_agregasi = """
SELECT
    Nation,
    COUNT(ID) AS Total_Players,
    AVG(OVR) AS Average_Rating
FROM
    eafc26
GROUP BY
    Nation
HAVING
    COUNT(ID) < 30
ORDER BY
    Average_Rating DESC;
"""
pd.read_sql(query_agregasi, conn)

                 Nation  Total_Players  Average_Rating
0                Malawi              3       77.666667
1                Jordan              2       75.000000
2            Mozambique              4       73.500000
3                 Libya              3       73.333333
4                  Chad              1       73.000000
..                  ...            ...             ...
87  Antigua and Barbuda              4       60.250000
88          Afghanistan              1       60.000000
89            Hong Kong              7       59.857143
90        Liechtenstein              1       58.000000
91            Gibraltar              1       52.000000

[92 rows x 3 columns]