In [2]:
import pandas as pd
import sqlite3

In [4]:
df = pd.read_csv('../dataset/EAFC26.csv')

In [5]:
conn = sqlite3.connect(':memory:')

In [6]:
df.to_sql('eafc26', conn, index=False)

17873

In [7]:
# Tabel A: Profil Pemain
df[['ID', 'Name', 'GENDER', 'Age', 'Nation', 'League', 'Team', 'Position']].to_sql('players', conn, index=False)
# Tabel B: Statistik Pemain
df[['ID', 'OVR', 'PAC', 'SHO', 'PAS', 'DRI', 'DEF', 'PHY']].to_sql('stats', conn, index=False)

print("Database siap digunakan")

Database siap digunakan

In [14]:
query_dasar = """
SELECT 
    Name, 
    Age, 
    Team, 
    OVR, 
    Finishing 
FROM 
    eafc26
WHERE 
    Age <= 23 AND Finishing > 85
ORDER BY 
    Finishing DESC
LIMIT 5;
"""
# Menjalankan query dan menampilkannya dalam format rapi
pd.read_sql(query_dasar, conn)

                 Name  Age               Team  OVR  Finishing
0    Melchie Dumornay   22         OL Lyonnes   86         89
1     Jude Bellingham   22        Real Madrid   90         88
2    Salma Paralluelo   22       FC Barcelona   84         88
3       Jamal Musiala   23  FC Bayern München   88         86
4  Agnes Beever-Jones   22            Chelsea   78         86

In [19]:
query_agregasi = """
SELECT
    Nation,
    COUNT(ID) AS Total_Players,
    AVG(OVR) AS Average_Rating
FROM
    eafc26
GROUP BY
    Nation
HAVING
    COUNT(ID) < 30
ORDER BY
    Average_Rating DESC;
"""
pd.read_sql(query_agregasi, conn)

                 Nation  Total_Players  Average_Rating
0                Malawi              3       77.666667
1                Jordan              2       75.000000
2            Mozambique              4       73.500000
3                 Libya              3       73.333333
4                  Chad              1       73.000000
..                  ...            ...             ...
87  Antigua and Barbuda              4       60.250000
88          Afghanistan              1       60.000000
89            Hong Kong              7       59.857143
90        Liechtenstein              1       58.000000
91            Gibraltar              1       52.000000

[92 rows x 3 columns]

In [ ]:
query_join = """
SELECT 
    p.Name, 
    p.Position, 
    p.Team, 
    s.OVR, 
    s.PAC
FROM 
    players p
INNER JOIN 
    stats s ON p.ID = s.ID
WHERE 
    s.PAC > 85 AND p.GENDER = 'men'
ORDER BY 
    s.PAC DESC
LIMIT 5;
"""
pd.read_sql(query_join, conn)

Empty DataFrame
Columns: [Name, Position, Team, OVR, PAC]
Index: []

In [30]:
query_tim = """
SELECT
    Name,
    Team,
    OVR,
    Nation
FROM
    eafc26
WHERE
    Team = 'Real Madrid'
"""
pd.read_sql(query_tim, conn)

                      Name         Team  OVR     Nation
0            Kylian Mbappé  Real Madrid   91     France
1          Jude Bellingham  Real Madrid   90    England
2        Federico Valverde  Real Madrid   89    Uruguay
3                 Vini Jr.  Real Madrid   89     Brazil
4         Thibaut Courtois  Real Madrid   89    Belgium
5          Antonio Rüdiger  Real Madrid   86    Germany
6   Trent Alexander-Arnold  Real Madrid   86    England
7            Caroline Weir  Real Madrid   85   Scotland
8                 Carvajal  Real Madrid   85      Spain
9                  Rodrygo  Real Madrid   85     Brazil
10           Linda Caicedo  Real Madrid   85   Colombia
11            Sara Däbritz  Real Madrid   84    Germany
12     Aurélien Tchouaméni  Real Madrid   84     France
13            Merle Frohms  Real Madrid   84    Germany
14            Éder Militão  Real Madrid   84     Brazil
15            Alba Redondo  Real Madrid   84      Spain
16       Eduardo Camavinga  Real Madrid   83     France
17                 Athenea  Real Madrid   83      Spain
18                    Misa  Real Madrid   82      Spain
19             David Alaba  Real Madrid   82    Austria
20            Dean Huijsen  Real Madrid   82      Spain
21            Maria Méndez  Real Madrid   82      Spain
22           Maëlle Lakrar  Real Madrid   82     France
23             Signe Bruun  Real Madrid   82    Denmark
24                  Brahim  Real Madrid   82    Morocco
25          Sandie Toletti  Real Madrid   81     France
26           Ferland Mendy  Real Madrid   81     France
27          Tere Abelleira  Real Madrid   81      Spain
28       Filippa Angeldahl  Real Madrid   81     Sweden
29           Antônia Silva  Real Madrid   81     Brazil
30            Andriy Lunin  Real Madrid   81    Ukraine
31           Dani Ceballos  Real Madrid   81      Spain
32              Arda Güler  Real Madrid   81     Turkey
33         Álvaro Carreras  Real Madrid   80      Spain
34                    Shei  Real Madrid   80      Spain
35           Naomie Feller  Real Madrid   80     France
36             Fran García  Real Madrid   79      Spain
37            Rocío Gálvez  Real Madrid   79      Spain
38             Eva Navarro  Real Madrid   78      Spain
39          Hanna Bennison  Real Madrid   77     Sweden
40      Franco Mastantuono  Real Madrid   77  Argentina
41                 Endrick  Real Madrid   77     Brazil
42                 Asencio  Real Madrid   77      Spain
43                  Yasmim  Real Madrid   75     Brazil
44          Sara Holmgaard  Real Madrid   71    Denmark
45                 Gonzalo  Real Madrid   69      Spain
46         Bella Andersson  Real Madrid   68     Sweden
47            Irune Dorado  Real Madrid   65      Spain
48           Fran González  Real Madrid   63      Spain

In [41]:
query_liga = """
SELECT
    Name,
    League,
    Nation
    Weight
FROM
    eafc26
WHERE
    League = 'Liga F Moeve'
"""
pd.read_sql(query_liga, conn)

                       Name        League         Weight
0           Alexia Putellas  Liga F Moeve          Spain
1            Aitana Bonmatí  Liga F Moeve          Spain
2    Caroline Graham Hansen  Liga F Moeve         Norway
3            Patri Guijarro  Liga F Moeve          Spain
4                 Mapi León  Liga F Moeve          Spain
..                      ...           ...            ...
282              Alba López  Liga F Moeve          Spain
283            Zoe Matthews  Liga F Moeve  United States
284               Alba Caño  Liga F Moeve          Spain
285           Marisa Garcia  Liga F Moeve          Spain
286                Mia León  Liga F Moeve           Peru

[287 rows x 3 columns]

In [34]:
query_nama = """
SELECT
    Name,
    Age,
    Nation
FROM
    eafc26
WHERE
    Name Like 'Kylian%'
"""
pd.read_sql(query_nama, conn)

             Name  Age   Nation
0   Kylian Mbappé   27   France
1  Kylian Kaïboué   27   France
2    Kyliane Dong   21   France
3  Kylian Kouassi   22  England